# Generated by Django 3.1.2 on 2020-10-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200929_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
